services:
  mysql:
    image: mysql:8.0 # MySQL のバージョンを指定
    platform: linux/amd64

# MySQL の設定値を指定
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# コンテナ内で使用する環境変数の値を指定
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS} # MySQL のルートユーザーのパスワード
      MYSQL_DATABASE: ${DATABASE} # MySQL に用意されている初期データベースの名前
      MYSQL_USER: ${USERNAME} # MySQL のユーザー名
      MYSQL_PASSWORD: ${USERPASS} # MySQL のユーザーパスワード
      TZ: 'Asia/Tokyo'

# コンテナの 3306 番ポートを、ローカルの 3306 番ポートにつなげる
    ports:
      - "3306:3306"
# コンテナ内にある MySQL に格納するデータを永続化させるために使用するボリュームを指定
    volumes:
      - db-volume:/var/lib/mysql
# ボリュームの作成
volumes:
  db-volume:
